import { HelpSection } from "@/app/components/HelpPanel";

export const ATTACK_SIMULATION_HELP: HelpSection[] = [
  {
    title: "What is an attack simulation?",
    content:
      "An attack simulation reproduces the behavior of a real attacker on a target system, without causing actual damage. The goal is to test defenses and identify vulnerabilities before a real attacker does.",
    tip: "Think of it like a fire drill: you simulate the threat so you're ready when it really happens.",
  },
  {
    title: "Step 1 — Choose a target asset",
    content:
      "An asset is a machine on the network (workstation, server, laptop…). By choosing a target, you define which system the simulated attack will run against. Only 'Online' assets can be targeted.",
    tip: "Start with a Windows workstation (WS-CORP-042) — it's the most common target in real-world attacks.",
  },
  {
    title: "Step 2 — Choose an adversary / TTP",
    content:
      "An adversary represents a real attacker group (e.g. APT29) with its techniques, tactics and procedures (TTP). TTPs are referenced in the MITRE ATT&CK framework under codes like T1566, T1078, etc.",
    tip: "APT29 is a known Russian state-sponsored group. Studying its TTPs prepares you for the most sophisticated threats.",
  },
  {
    title: "Understanding MITRE TTPs",
    content:
      "MITRE ATT&CK is a global knowledge base documenting attack techniques. Each T#### code corresponds to a specific technique: T1566 = Phishing, T1078 = Valid Accounts, T1486 = Data Encryption (ransomware).",
    tip: "Visit attack.mitre.org to explore each technique in detail with real-world examples.",
  },
  {
    title: "Step 3 — Confirm & Launch",
    content:
      "Before launching, check the checklist: the asset must be online, the adversary profile loaded, and the SIEM active to capture events generated by the simulation.",
    tip: "The SIEM (Ludus) will record all simulated actions. After the simulation, analyze the generated alerts to understand what a real attacker could have done.",
  },
];

export const DETECTION_HELP: HelpSection[] = [
  {
    title: "What is a SIEM alert?",
    content:
      "A SIEM (Security Information and Event Management) collects logs from all your systems and generates alerts when it detects suspicious behavior. Each alert corresponds to an abnormal event detected on an asset.",
    tip: "An alert is not necessarily a real attack — it's a signal that warrants investigation. It's up to you to decide whether it's a true positive or a false positive.",
  },
  {
    title: "Reading an alert — key fields",
    content:
      "Each alert contains: severity (Critical/High/Medium/Low), the targeted asset, the associated MITRE TTP, timestamp, and detection source. This information lets you prioritize and contextualize the threat.",
    tip: "Always start with 'Critical' alerts, then 'High'. A 'Medium' alert on a DC (Domain Controller) is often more dangerous than a 'High' on a laptop.",
  },
  {
    title: "Severity levels",
    content:
      "Critical = probable compromise, immediate action required. High = advanced suspicious activity, urgent investigation. Medium = abnormal behavior, to be monitored. Low = informational, may be a false positive.",
    tip: "In a real SOC, a Critical alert must be handled within 15 minutes.",
  },
  {
    title: "Investigating an alert",
    content:
      "Investigation involves analyzing raw logs, understanding the event chain (kill chain), identifying whether other assets are affected, and determining if the alert is a true or false positive.",
    tip: "Always look at the 'Raw Log' — technical details (source IP, user, executed command) are essential to understand what really happened.",
  },
  {
    title: "Rule Tuning — refining rules",
    content:
      "Rule Tuning lets you adjust detection rules to reduce false positives (alerts on legitimate behavior) or false negatives (undetected attacks). It's a permanent balancing act.",
    tip: "If you receive many Medium alerts on the same asset for the same reason, it's often a good candidate for tuning.",
  },
];

export const RULE_TUNING_HELP: HelpSection[] = [
  {
    title: "What is a detection rule?",
    content:
      "A detection rule is a set of conditions that, if met in the logs, generate an alert. It defines what to monitor (log source), how to detect it (conditions), and what severity to assign.",
    tip: "A good SOC has hundreds of active rules. Quality beats quantity: 50 precise rules are better than 500 noisy ones.",
  },
  {
    title: "The Sigma YAML format",
    content:
      "CyberLab uses the Sigma format — an open-source standard for writing portable detection rules. A Sigma rule contains: title, logsource (where the logs come from), detection (the conditions), and level (the severity).",
    tip: "Sigma is portable: the same rule can be converted for Splunk, Elastic, QRadar, or any other SIEM. It's the industry reference format.",
  },
  {
    title: "Rule structure — detection",
    content:
      "The 'detection' block is the heart of the rule. It contains 'selections' (groups of conditions) and a 'condition' that combines them. Operators |contains, |startswith, |endswith filter field values.",
    tip: "Use 'filter' to exclude known false positives: 'condition: selection and not filter'. It's cleaner than complicating the selections.",
  },
  {
    title: "False positives — falsepositives",
    content:
      "The 'falsepositives' field documents legitimate behaviors that could trigger the rule. This is crucial so the analyst knows when to ignore an alert without deep investigation.",
    tip: "Always list known false positives before activating a rule. This prevents 'alert fatigue' that leads analysts to ignore all alerts.",
  },
  {
    title: "Test before activating",
    content:
      "Leave a new rule in 'inactive' status and test it by simulating it with Caldera before activating. Verify that it triggers on the real attack and not on legitimate traffic.",
    tip: "Ideal workflow: create (inactive) → test with simulation → adjust → activate. Never activate an untested rule in production.",
  },
];
